// apps/frontend/components/room/trophy-frame.tsx
import * as THREE from "three";
import { useRef, useState, useEffect } from "react";
import { useFrame } from "@react-three/fiber";

// Trophy aspect ratios: medals ~1:1, bibs ~1.3:1 (landscape)
const FRAME_HEIGHT = 0.8;
const MEDAL_ASPECT = 1;
const BIB_ASPECT = 1.3;

interface TrophyFrameProps {
  textureUrl: string;
  trophyType?: "medal" | "bib";
  position: [number, number, number];
  rotation: [number, number, number];
  editable?: boolean;
  onPress?: () => void;
}

export function TrophyFrame({
  textureUrl,
  trophyType = "medal",
  position,
  rotation,
  editable = false,
  onPress,
}: TrophyFrameProps) {
  const meshRef = useRef<THREE.Mesh>(null!);
  const [texture, setTexture] = useState<THREE.Texture | null>(null);
  const [hovered, setHovered] = useState(false);

  useEffect(() => {
    if (!textureUrl) return;
    const loader = new THREE.TextureLoader();
    loader.load(textureUrl, (tex) => {
      tex.colorSpace = THREE.SRGBColorSpace;
      setTexture(tex);
    });
  }, [textureUrl]);

  const aspect = trophyType === "bib" ? BIB_ASPECT : MEDAL_ASPECT;
  const width = FRAME_HEIGHT * aspect;

  // Subtle idle sway
  useFrame((state) => {
    if (!meshRef.current) return;
    meshRef.current.rotation.z = Math.sin(state.clock.elapsedTime * 0.5) * 0.01;
  });

  if (!texture) return null;

  return (
    <mesh
      ref={meshRef}
      position={position}
      rotation={rotation}
      castShadow
      onClick={editable ? onPress : undefined}
      onPointerOver={editable ? () => setHovered(true) : undefined}
      onPointerOut={editable ? () => setHovered(false) : undefined}
    >
      <planeGeometry args={[width, FRAME_HEIGHT]} />
      <meshStandardMaterial
        map={texture}
        transparent
        side={THREE.DoubleSide}
        emissive={hovered && editable ? new THREE.Color(0xffcc66) : undefined}
        emissiveIntensity={hovered && editable ? 0.3 : 0}
      />
    </mesh>
  );
}

// apps/frontend-ionic/src/app/features/room/components/trophy-frame/trophy-frame.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  input,
  output,
  signal,
  viewChild,
  ElementRef,
} from '@angular/core';
import { extend, injectBeforeRender, NgtArgs } from 'angular-three';
import { textureResource } from 'angular-three-soba/loaders';
import {
  Mesh,
  PlaneGeometry,
  MeshStandardMaterial,
  DoubleSide,
  Color,
  SRGBColorSpace,
} from 'three';

extend({ Mesh, PlaneGeometry, MeshStandardMaterial });

// Trophy aspect ratios: medals ~1:1, bibs ~1.3:1 (landscape)
const FRAME_HEIGHT = 0.8;
const MEDAL_ASPECT = 1;
const BIB_ASPECT = 1.3;

@Component({
  selector: 'app-trophy-frame',
  standalone: true,
  imports: [NgtArgs],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    @if (texture.value(); as tex) {
      <ngt-mesh
        #meshRef
        [position]="position()"
        [rotation]="rotation()"
        [castShadow]="true"
        (click)="onPress()"
        (pointerover)="onHover(true)"
        (pointerout)="onHover(false)"
      >
        <ngt-plane-geometry *args="[width(), FRAME_HEIGHT]" />
        <ngt-mesh-standard-material
          [map]="tex"
          [transparent]="true"
          [side]="DoubleSide"
          [emissive]="hovered() && editable() ? hoverColor : undefined"
          [emissiveIntensity]="hovered() && editable() ? 0.3 : 0"
        />
      </ngt-mesh>
    }
  `,
})
export class TrophyFrameComponent {
  textureUrl = input.required<string>();
  trophyType = input<'medal' | 'bib'>('medal');
  position = input<[number, number, number]>([0, 1.5, 0]);
  rotation = input<[number, number, number]>([0, 0, 0]);
  editable = input(false);
  pressed = output<void>();

  hovered = signal(false);
  readonly DoubleSide = DoubleSide;
  readonly FRAME_HEIGHT = FRAME_HEIGHT;
  readonly hoverColor = new Color(0xffcc66);

  meshRef = viewChild<ElementRef<Mesh>>('meshRef');

  // Load texture via angular-three-soba resource
  texture = textureResource(() => this.textureUrl(), {
    onLoad: (tex) => {
      tex.colorSpace = SRGBColorSpace;
    },
  });

  width(): number {
    const aspect = this.trophyType() === 'bib' ? BIB_ASPECT : MEDAL_ASPECT;
    return FRAME_HEIGHT * aspect;
  }

  constructor() {
    // Subtle idle sway animation
    injectBeforeRender(({ clock }) => {
      const mesh = this.meshRef()?.nativeElement;
      if (mesh) {
        mesh.rotation.z = Math.sin(clock.elapsedTime * 0.5) * 0.01;
      }
    });
  }

  onPress(): void {
    if (this.editable()) {
      this.pressed.emit();
    }
  }

  onHover(state: boolean): void {
    if (this.editable()) {
      this.hovered.set(state);
    }
  }
}
